config/routes.rb
resources :file_servers

# post '/issues/scan_files', :to => 'issues#scan_files'
patch '/:object_type/:object_id/scanfiles', to: 'attachments#scan_files', as: :scan_files

mount DelayedJobWeb => "/delayed_job", anchor: false, via: [:get, :post]

app/views/attachments/_filelinks.html.erb
<tr>
  <td>
    <%= link_to_attachment attachment, class: 'icon icon-attachment' -%>
    <span class="size">(<%= Attachment::FOLDER_FILESIZE == attachment.filesize ? l(:label_folder) : number_to_human_size(attachment.filesize) %>)</span>
    <%= link_to_attachment(attachment, class: 'icon-only icon-download', title: l(:button_download), download: true) -%>
  </td>
  <td><%= attachment.description unless attachment.description.blank? %></td>
  <td>
    <% if options[:author] %>
        <span class="author"><%= attachment.author %>, <%= format_time(attachment.created_on) %></span>
    <% end %>
    <%= " (#{l(:label_manually_uploaded)})" if attachment.author_id == 0 %>
  </td>
  <td>
    <% if options[:deletable] %>
        <%= link_to l(:button_delete), attachment_path(attachment),
                    :data => {:confirm => l(:text_are_you_sure)},
                    :method => :delete,
                    :class => 'delete icon-only icon-del',
                    :title => l(:button_delete) %>
    <% end %>
    <%= content_tag('span', '-' , class: 'icon icon-ftp-attachment') if @scan_result && @scan_result[:new].include?(attachment) %>
  </td>
</tr>

app/views/attachments/_ftpscanbrowse.html.erb
<%= stylesheet_link_tag 'fileserverlayout.css', plugin: 'file_servers' %>
<p>
  <strong><%= l(:attach_files) %></strong> (
  <%= if container.project.file_server.autoscan
        ''
      else
        link_to(l(:attach_rescan), scan_files_path(container.class.name.underscore.pluralize, container.id,
                                                   back_url: request.original_url), method: :patch, remote: true ) + " / "
      end %>
  <%= link_to(l(:attach_browse), container.alien_files_folder(true), :target => "_blank") %>
  )</p>
<% if attachments && attachments.blank? %>
  <div class="attachments">
    <table>
    </table>
  </div>
<% end -%>

app/views/attachments/_links.html.erb
<div class="attachments">
<% if @scan_result && @scan_result[:error] %>
  <div class='flash error'><%= @scan_result[:error] %></div>
<% end %>

<div class="contextual">
  <%= link_to(l(:label_edit_attachments),
        container_attachments_edit_path(container),
              :title => l(:label_edit_attachments),
              :class => 'icon-only icon-edit'
             ) if options[:editable] %>
</div>
<table>
<% for attachment in attachments %>
<tr>
  <td>
    <%= link_to_attachment attachment, class: 'icon icon-attachment' -%>
    <span class="size">(<%= Attachment::FOLDER_FILESIZE == attachment.filesize ? l(:label_folder) : number_to_human_size(attachment.filesize) %>)</span>
    <%= link_to_attachment(attachment, class: 'icon-only icon-download', title: l(:button_download), download: true) -%>
  </td>
  <td><%= attachment.description unless attachment.description.blank? %></td>
  <td>
    <% if options[:author] %>
      <span class="author"><%= attachment.author %>, <%= format_time(attachment.created_on) %></span>
    <% end %>
    <%= " (#{l(:label_manually_uploaded)})" if attachment.author_id == 0 %>
  </td>
  <td>
  <% if options[:deletable] %>
      <%= link_to l(:button_delete), attachment_path(attachment),
                                         :data => {:confirm => l(:text_are_you_sure)},
                                         :method => :delete,
                  :class => 'delete icon-only icon-del',
                                         :title => l(:button_delete) %>
  <% end %>
  <%= content_tag('span', '' , class: 'icon icon-ftp-attachment') if @scan_result && @scan_result[:new].include?(attachment) %>
  </td>
</tr>
<% end %>
</table>
<% if defined?(thumbnails) && thumbnails %>
  <% images = attachments.select(&:thumbnailable?) %>
  <% if images.any? %>
  <div class="thumbnails">
    <% images.each do |attachment| %>
      <div><%= thumbnail_tag(attachment) %></div>
    <% end %>
  </div>
  <% end %>
<% end %>
</div>

app/views/attachments/scan_files.js.erb
<% if @attachments_new && !@attachments_new.empty? %>
  <% @attachments_new.each do |attachment| %>
    $('.attachments table').append('<%= escape_javascript(render :partial => "attachments/filelinks", :locals => {:attachment => attachment, :options => @options}) %>');
  <% end %>
<% end %>

<% if @attachments_deled && !@attachments_deled.empty? %>
  <% @attachments_deled.each do |attachment| %>
    $( "a:contains('<%= j attachment %>')").parents('tr').remove();
  <% end %>
<% end %>

<% if @scan_result[:error].present? %>
  alert(<%= j @scan_result[:error] %>);
<% end %>