config/routes.rb
resources :file_servers

# post '/issues/scan_files', :to => 'issues#scan_files'
patch '/:object_type/:object_id/scanfiles', to: 'attachments#scan_files', as: :scan_files

mount DelayedJobWeb => "/delayed_job", anchor: false, via: [:get, :post]

app/models/file_server.rb
class FileServer < ActiveRecord::Base
  unloadable
  # include Redmine::SafeAttributes

  has_many :projects, :dependent => :nullify
  has_many :attachment, :dependent => :nullify

  store :format_store
  store_accessor :format_store, :sudo_login, :sudo_password

  PROTOCOL_FTP = 0

  PROTOCOLS = { PROTOCOL_FTP => { :name => "ftp", :label => :label_file_server_ftp, :order => 1}
  }.freeze


  validates_presence_of :name
  validates_length_of :name, :maximum => 50
  validates_presence_of :address
  validates_length_of :address, :maximum => 120
  validates_numericality_of :port, :allow_nil => true
  validates_length_of :root, :maximum => 120
  validates_length_of :login, :maximum => 40
  validates_length_of :password, :maximum => 40
  validates_inclusion_of :protocol, :in => PROTOCOLS.keys

  attr_accessible :name, :protocol, :address, :port, :root, :login, :password,
                  :autoscan, :is_public, :project_ids, :ftp_active, :sudo_login,
                  :sudo_password, :if => lambda {|project, user| user.admin? }

  require 'net/ftp'
  require 'stringio'
  # require 'uri'

  def initialize(attributes=nil, *args)
    super
    if new_record?
      # set default values for new records only
      self.protocol ||= PROTOCOLS.keys[0]
    end
  end

  def to_s; self.name end

  def type_name
    PROTOCOLS[self.protocol][:name]
  end

  def type_label
    l(PROTOCOLS[self.protocol ||= PROTOCOLS.keys[0]][:label])
  end

  def is_passive?
    !ftp_active
  end

  def ftp_active
    format_store[:ftp_active] == '1'
  end

  def ftp_active=(val)
    format_store[:ftp_active] = val
  end

  def ftpurl_for(relative_path,full,root_included=false,show_credentials=true)
    url = []
    if full
      ftp_credentials = "ftp://"
      if show_credentials
        ftp_credentials += self.login if self.login
        ftp_credentials += ":" + self.password if self.password && self.is_public
        ftp_credentials += "@" if self.login || (self.password && self.is_public)
      end
      ftp_credentials += self.address
      ftp_credentials += ":" + self.port.to_s unless self.port.nil?
      url << ftp_credentials
    end
    url << self.root if (!self.root.blank? && !root_included)
    url << relative_path
    logger.debug("url_for url -- #{url} ---")
    url.compact.join('/')
  end

  def make_directory(path,ftp=nil,ftp_close=true)
    ftp = ftp_connection if ftp.nil?
    return if ftp.nil?
    ret = false
    begin
      logger.debug("make_directory Change Directory - #{path}")
      begin
        ftp.chdir path
      rescue
        logger.debug("make_directory Change Directory with / - /#{path}")
        ftp.chdir "/#{path}"
      end
      ret = true
    rescue
      begin
        path.split("/").each do |d|
          logger.debug("make_directory create Directory - #{d}")
          begin
            ftp.mkdir d
          rescue
          end
          ftp.chdir d
        end
        ftp.close if ftp_close
        ret = true
      rescue Exception => e
        logger.debug("FTP FILESERVER : make_directory - #{e}")
      end
    end
    ret
  end

  def scan_directory(path,attched_files,create_it=false)
    ftp = ftp_connection
    return if ftp.nil?

    files = {}
    begin
      if create_it
        make_directory(path,ftp,false)
      else
        ftp.chdir path
      end

      ftp.passive = true if is_passive?
      # files = ftp.nlst

      ftp.nlst.each do |file|
        logger.debug("scan_directory File - #{file}")
        if !attched_files.include? file
          begin
            files[file] = ftp.size(file) # The command fails to get size of the directory.
          rescue
            files[file] = Attachment::FOLDER_FILESIZE # Assume its a directory.
          end
          logger.debug("scan_directory File Size - #{files[file]}")
        else
          files[file] = 0 # Skip getting file size
        end
      end
    rescue Exception => e
      logger.debug("FTP FILESERVER : scan_directory - #{e}")
    end
    ftp.close
    files
  end

  def upload_file(source_file_path, target_directory_path, target_file_name, ret_filesize=false)
    ftp = ftp_connection
    return if ftp.nil?
    logger.debug("upload_file - #{source_file_path} #{target_directory_path}")
    ret = false
    begin
      make_directory(target_directory_path,ftp,false)
      begin
        ftp.chdir target_directory_path
      rescue
        logger.debug("upload_file Change Directory with / - /#{target_directory_path}")
        ftp.chdir "/#{target_directory_path}"
      end
      ftp.passive = true if is_passive?
      ftp.putbinaryfile source_file_path,target_file_name
      ret = ret_filesize ? ftp.size(target_file_name) : true
    rescue Exception => e
      raise "FTP Exception: #{e}" if ret_filesize
      logger.debug("FTP FILESERVER : upload_file - #{e}")
    end
    ftp.close
    ret
  end

  def delete_file(file_directory, file_name)
    ftp = ftp_connection(true)
    return if ftp.nil?

    ret = false
    begin
      ftp.chdir file_directory
      ftp.delete file_name
      ret = true
    rescue Exception => e
      logger.debug("FTP FILESERVER : delete_file - #{e}")
    end
    ftp.close
    ret
  end

  def self.crypt_password(pwd)
    pwd.nil? ? "" : pwd
  end

  def decrypted_password
    self.password
  end

  def puttextcontent(content, remotefile)
    target_directory_path = File.dirname(remotefile)
    target_file_name      = File.basename(remotefile)
    logger.debug("puttextcontent - #{target_directory_path} #{remotefile}")
    ftp = ftp_connection
    return if ftp.nil?
    ret = false

    f = StringIO.new(content)
    begin
      make_directory(target_directory_path,ftp,false)
      ftp.storbinary("STOR " + target_file_name, f, 8192)
    rescue Exception => e
      logger.debug("FTP FILESERVER : puttextcontent - #{e}")
    ensure
      f.close
      ftp.close
      ret = true
    end
    ret
  end

  def move_file_to_dir(source_file_path,target_file_path)
    return unless source_file_path != target_file_path
    ftp = ftp_connection
    return if ftp.nil?
    ret = false
    begin
      logger.debug("move_file_to_dir source_file_path #{source_file_path} --target_file_path - #{target_file_path}")
      ftp.rename(source_file_path,target_file_path)
      ret = true
    rescue Exception => e
      logger.debug("FTP FILESERVER : move_file_to_dir - #{e}")
    end
    ftp.close
    ret
  end

  def readftpFile(ftpremotefile, localfile=nil)
    ftp = ftp_connection
    return if ftp.nil?

    ret = ""
    begin
      ret = ftp.getbinaryfile(ftpremotefile, localfile)
    rescue Exception => e
      logger.debug("FTP FILESERVER : readftpFile - #{e}")
    end
    ftp.close
    ret
  end


  def ftp_file_exists?(file_directory, filename)
    ftp = ftp_connection
    return if ftp.nil?

    ret = false
    begin
      ftp.chdir(file_directory)
      ret = true if not ftp.nlst(filename).empty?
    rescue Exception => e
      logger.debug("FTP FILESERVER : ftp_file_exists - #{e}")
    end
    ftp.close
    ret
  end

  private
  def ftp_connection(delete=false)
    ftp = nil
    begin
      ftp = Net::FTP.new
      begin
        Timeout.timeout(5) do
          if port.nil?
            ftp.connect address
          else
            ftp.connect address, port
          end
        end
        resp = if delete && sudo_login.present? && sudo_password.present?
                 ftp.login(sudo_login, sudo_password)
               else
                 ftp.login(login, decrypted_password)
               end
        logger.debug("FTP FILESERVER : ftp_connection - #{resp}")
        ftp.passive = true if is_passive?
      rescue Timeout::Error => e
        logger.debug("FTP FILESERVER : ftp_connection - #{e}")
        ftp = nil
      end
    rescue
      ftp = nil
    end
    ftp
  end
end

app/controllers/file_servers_controller.rb
class FileServersController < ApplicationController
  unloadable

  layout 'admin'
  before_filter :require_admin

  helper :file_servers

  def index
    @file_servers = FileServer.all.order("address ASC")
  end

  def new
    @file_server = FileServer.new
    @projects = Project.all
  end

  def create
    # attrs = file_server_params
    attrs = params[:file_server]
    attrs[:password] = FileServer::crypt_password(attrs[:password])
    @file_server = FileServer.new(attrs)
    if @file_server.save
      flash[:notice] = l(:notice_successful_create)
      redirect_to :action => 'index', :tab => @file_server.class.name
    else
      render 'new'
    end
  end

  def edit
    @file_server = FileServer.find(params[:id])
    @projects = Project.all
  end

  def update
    @file_server = FileServer.find(params[:id])
    attrs = params[:file_server]
    attrs[:password] = attrs[:password] == '********' ? @file_server.password : FileServer::crypt_password(attrs[:password])
    if @file_server.update_attributes(attrs)
      flash[:notice] = l(:notice_successful_update)
      redirect_to :action => 'index', :tab => @file_server.class.name
      return
    end
  end

  def destroy
    @file_server = FileServer.find(params[:id]).destroy
    redirect_to :action => 'index', :tab => @file_server.class.name
  rescue
    flash[:error] = l(:error_can_not_delete_file_server)
    redirect_to :action => 'index'
  end

  private
  def file_server_params
    params.require(:file_server).permit(:name, :protocol, :address, :port,
                                        :root, :login, :password, :autoscan,
                                        :is_public, :project_ids, :sudo_login,
                                        :sudo_password)
  end
end

app/helpers/file_servers_helper.rb
module FileServersHelper
  def file_server_project_options_for_select(file_server)
    projects = Project.find(:all,
                 :conditions => "file_server_id is null or file_server_id != #{file_server.id}",
                 :order => 'name')
    options_for_select(projects.collect {|p| [p.name + (p.file_server.nil? ? "" : "   (#{l(:label_file_server_current)}: #{p.file_server.name})") , p.id]})
  end
end

app/views/file_servers/_form.html.erb
<%= stylesheet_link_tag 'fileserverlayout', plugin: 'file_servers' %>
<%= error_messages_for 'file_server' %>

<h3><%=l(:label_file_server_settings)%></h3>
<div class="splitcontentleft">
  <div class="box tabular">

  <!--[form:file_server]-->
    <p><%= f.text_field :name, :required => true%></p>
    <p>
    <% protocols = FileServer::PROTOCOLS %>
    <%= f.select :protocol, protocols.keys.sort{|x,y| protocols[x][:order] <=> protocols[y][:order]}.collect{|k|
      [l(protocols[k][:label]), k]}, :required => true %>
    </p>
    <p><%= f.text_field :address, label: l(:field_server_address), :required => true%></p>
    <p><%= f.text_field :port%></p>
    <p><%= f.text_field :root%></p>
    <p><%= f.text_field :login%></p>
    <p><%= f.password_field :password, :value => @file_server.password %></p>
    <p><%= f.check_box :autoscan %></p>
    <p><%= f.check_box :is_public %></p>

    <p><%= f.check_box :ftp_active %></p>
    <p><%= f.text_field :sudo_login%></p>
    <p><%= f.password_field :sudo_password, :value => @file_server.sudo_password %></p>
  </div>
  <%= submit_tag !@file_server.new_record? ? l(:button_save) : l(:button_add) %>
</div>
<div class="splitcontentright">
<% if @projects && @projects.any? %>
  <fieldset class="box" id="file_servers_project_ids">
    <legend><%= l(:label_project_plural) %></legend>
    <%= render_project_nested_lists(@projects) do |p|
      content_tag('label', check_box_tag('file_server[project_ids][]', p.id, @file_server.projects.to_a.include?(p),
        :id => nil) + ' ' + h(p))
    end %>
    <%= hidden_field_tag('file_server[project_ids][]', '', :id => nil) %>
    <p><%= check_all_links 'file_servers_project_ids' %></p>
  </fieldset>
<% end %>
</div>

app/views/file_servers/edit.html.erb
<%= title [l(:label_file_server_plural), file_servers_path], @file_server.name %>


<%= labelled_form_for @file_server do |f| %>
<%= render :partial => 'form', :locals => { :f => f } %>
<% end %>

app/views/file_servers/index.html.erb
<div class="contextual">
<%= link_to l(:label_file_server_new), new_file_server_path, :class => 'icon icon-add' %>
<%#= link_to l(:label_dry_clean_up), file_server_cleanup_path(:type => 'dry'), :method => 'post', :remote => true, :class => 'icon icon-del' %>
<%#= link_to l(:label_clean_up), file_server_cleanup_path(:type => 'delete'), :method => 'post', :remote => true, :class => 'icon icon-del' %>
</div>

<h2><%=l(:label_file_server_plural)%></h2>

<table class="list">
  <thead><tr>
  <th><%=l(:field_name)%></th>
  <th><%=l(:field_server_address)%></th>
  <th><%=l(:field_protocol)%></th>
  <th><%=l(:field_login)%></th>
  <th><%=l(:field_root)%></th>
  <th><%=l(:label_scan_mode)%></th>
  <th><%=l(:label_project_plural)%></th>
  <th></th>
  </tr></thead>
  <tbody>
<% @file_servers.each do |file_server| %>
  <tr class="<%= cycle("odd", "even") %>">
  <td align=center><%= link_to file_server.name, :action => 'edit', :id => file_server %></td>
  <td align=center><%= h file_server.address %><%= ":" + file_server.port.to_s unless file_server.port.nil? %></td>
  <td align=center><%= h file_server.type_label %></td>
  <td align=center><%= h file_server.login %></td>
  <td align=center><%= h file_server.root %></td>
  <td align=center><%= file_server.autoscan ? l(:label_scan_auto) : l(:label_scan_manual) %></td>
  <td align=left>
	<% file_server.projects.order('lft ASC').each do |project| %>
	  <%= project.proj_tree_path %><br />
	<% end %>
  </td>
  <td class="buttons">
    <%= link_to l(:button_delete), file_server, method: :delete, data: {confirm: l(:text_are_you_sure)},
                :class => 'icon icon-del' %>
  </td>
  </tr>
<% end %>
  </tbody>
</table>

<% html_title(l(:label_file_server_plural)) -%>

app/views/file_servers/new.html.erb
<%= title [l(:label_file_server_plural), file_servers_path], l(:label_file_server_new) %>

<%= labelled_form_for @file_server do |f| %>
<%= render :partial => 'form', :locals => { :f => f } %>
<% end %>